/*
 * EEL4511_DAC.c
 *
 *  Created on: Oct 17, 2016
 *      Author: Adrian
 */
#include<DSP28x_Project.h>
#include "../include/EEL4511_DAC.h"

void Init_McBSPa_DAC(void)
{
	EALLOW;

	SysCtrlRegs.PCLKCR0.bit.MCBSPAENCLK |= 1;//enable McBSPA clock signal for SRGR

	GpioCtrlRegs.GPAMUX2.bit.GPIO20 = 2; 	//GPIO20 = MDXA
	GpioCtrlRegs.GPAMUX2.bit.GPIO22 = 2; 	//GPIO22 = MCLKXA
	GpioCtrlRegs.GPAMUX2.bit.GPIO23 = 2; 	//GPIO23 = MFSXA

	//Step 1. Place the transmitter and receiver in reset.
	McbspaRegs.SPCR2.bit.XRST 	= 0;
	McbspaRegs.SPCR1.bit.RRST   = 0;

	//Step 2. Place the sample rate generator in reset.
	McbspaRegs.SPCR2.bit.GRST   = 0;

	//Step 3. Program registers that affect SPI operation.
	McbspaRegs.SPCR1.bit.CLKSTP = 2;   	 	//CLKSTP bits in SPRC1 = 0b10
	McbspaRegs.PCR.bit.CLKXP    = 1;		//CLKXP in PCR = 0b1
	McbspaRegs.PCR.bit.CLKRP    = 0;		//CLKRP in PCR = 0b0
	McbspaRegs.PCR.bit.CLKXM    = 1;		//CLKXM in PCR = 0b1 (McBSP = master)
	McbspaRegs.PCR.bit.SCLKME   = 0;		//clock generated by the sample rate generator (CLKG) is derived from the CPU clock.
	McbspaRegs.SRGR2.bit.CLKSM  = 1;
	McbspaRegs.SRGR1.bit.CLKGDV = 8;		//divide clock by 8
	McbspaRegs.PCR.bit.FSXM	    = 1;        //FSX is output
	McbspaRegs.PCR.bit.FSXP     = 1;		//FSX is active low
	McbspaRegs.SRGR2.bit.FSGM   = 0;        //FSX = ~SS chip select
	McbspaRegs.XCR2.bit.XPHASE  = 0;
	McbspaRegs.RCR2.bit.RPHASE  = 0;
	McbspaRegs.XCR1.bit.XFRLEN1 = 0;
	McbspaRegs.XCR1.bit.XWDLEN1 = 2;

	//Step 4. Enable the sample rate generator.
	McbspaRegs.SPCR2.bit.GRST   = 1;

	//Step 5. Enable the transmitter and receiver.
	McbspaRegs.SPCR2.bit.XRST 	= 1;
	McbspaRegs.SPCR1.bit.RRST   = 1;

	EDIS;
}

void DAC_out(Uint16 value)
{
	EALLOW;
	//while(McbspaRegs.SPCR2.bit.XRDY == 0);
	McbspaRegs.DXR1.all = value;
	EDIS;

	return;
}
